
project_id = "zkyqdwmwignohqujlnxf"

[functions.openai-assistant]
verify_jwt = false


[functions.ask-agent]
enabled = true
verify_jwt = true
import_map = "./functions/ask-agent/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ask-agent/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ask-agent/*.html" ]
