// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkyqdwmwignohqujlnxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreXFkd213aWdub2hxdWpsbnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjU3MTQsImV4cCI6MjA2MjIwMTcxNH0.gFrKXlpvdzVb4awwnTMKksYDjqx9Z2QRm3eSk2OxhO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);